services:
  comercial-map-api:
    build: .
    container_name: comercial_map_api
    volumes:
      - .:/app
    ports:
      - "58900:8000"
    env_file:
      - .env
    depends_on:
      - comercial-map-api-postgres
    command: sleep infinity
    # command: ["uvicorn", "comercial_map_api.asgi:application", "--workers", "4", "--host", "0.0.0.0", "--port", "8000"]

  comercial-map-api-postgres:
    image: postgres:13.3
    container_name: comercial_map_api_postgres
    volumes:
      - ./docker_data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=comercial_map_api
      - POSTGRES_USER=comercial_map_api
      - POSTGRES_PASSWORD=comercial_map_api
    ports:
      - "5432:5432"
